language: ruby
rvm:
 - 2.5.5

services:
  - postgresql

script:
  - bin/setup
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec spinach

notifications:
  email:
    on_success: never
    on_failure: never
