language: ruby
rvm:
 - 2.5.5

services:
  - postgresql

script:
  - gem install bundler:1.17.3
  - bin/setup
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email:
    on_success: never
    on_failure: never
